openapi: 3.0.1
info:
  title: TRIDENT_Project
  description: "\r\nAn ASP.NET Core 6 Web API for TRIDENT_Project.  \r\nSome useful links:\r\n- [The TRIDENT_Project repository](https://github.com/suzijie860706/TRIDENT_Project)"
  termsOfService: https://example.com/terms
  contact:
    name: Example Contact
    url: https://example.com/contact
  license:
    name: Example License
    url: https://example.com/license
  version: v1
paths:
  /api/Courses:
    get:
      tags:
        - Courses
      summary: 課程列表
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
    post:
      tags:
        - Courses
      summary: 建立新課程
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseParamenter'
            example:
              courseName: 國文
              professorId: 1
          text/json:
            schema:
              $ref: '#/components/schemas/CourseParamenter'
            example:
              courseName: 國文
              professorId: 1
          application/*+json:
            schema:
              $ref: '#/components/schemas/CourseParamenter'
            example:
              courseName: 國文
              professorId: 1
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Course'
              example:
                id: 1
                courseName: 國文
                description: null
                professorId: 1
                createdDate: '2024-10-14T11:39:13.9781036+08:00'
                updatedDate: '2024-10-14T11:39:13.9781038+08:00'
                startTime: null
                endTime: null
                professor: null
                studentCourses: []
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
              example:
                id: 1
                courseName: 國文
                description: null
                professorId: 1
                createdDate: '2024-10-14T11:39:13.9781036+08:00'
                updatedDate: '2024-10-14T11:39:13.9781038+08:00'
                startTime: null
                endTime: null
                professor: null
                studentCourses: []
            text/json:
              schema:
                $ref: '#/components/schemas/Course'
              example:
                id: 1
                courseName: 國文
                description: null
                professorId: 1
                createdDate: '2024-10-14T11:39:13.9781036+08:00'
                updatedDate: '2024-10-14T11:39:13.9781038+08:00'
                startTime: null
                endTime: null
                professor: null
                studentCourses: []
  /api/Courses/{id}:
    get:
      tags:
        - Courses
      summary: 取得特定課程
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '204':
          description: No Content
    put:
      tags:
        - Courses
      summary: 更新課程內容
      parameters:
        - name: id
          in: path
          description: 課程id
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
            example:
              id: 1
              courseName: 國文
              description: null
              professorId: 1
              createdDate: '2024-10-14T11:39:13.9802302+08:00'
              updatedDate: '2024-10-14T11:39:13.980232+08:00'
              startTime: null
              endTime: null
              professor: null
              studentCourses: []
          text/json:
            schema:
              $ref: '#/components/schemas/Course'
            example:
              id: 1
              courseName: 國文
              description: null
              professorId: 1
              createdDate: '2024-10-14T11:39:13.9802302+08:00'
              updatedDate: '2024-10-14T11:39:13.980232+08:00'
              startTime: null
              endTime: null
              professor: null
              studentCourses: []
          application/*+json:
            schema:
              $ref: '#/components/schemas/Course'
            example:
              id: 1
              courseName: 國文
              description: null
              professorId: 1
              createdDate: '2024-10-14T11:39:13.9802302+08:00'
              updatedDate: '2024-10-14T11:39:13.980232+08:00'
              startTime: null
              endTime: null
              professor: null
              studentCourses: []
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    delete:
      tags:
        - Courses
      summary: 刪除課程
      parameters:
        - name: id
          in: path
          description: 課程id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /api/Professors:
    get:
      tags:
        - Professors
      summary: 授課講師列表
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Professor'
    post:
      tags:
        - Professors
      summary: 建立新講師
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfessorParamenter'
            example:
              name: 王教授
              email: asdasd@gamil.com
          text/json:
            schema:
              $ref: '#/components/schemas/ProfessorParamenter'
            example:
              name: 王教授
              email: asdasd@gamil.com
          application/*+json:
            schema:
              $ref: '#/components/schemas/ProfessorParamenter'
            example:
              name: 王教授
              email: asdasd@gamil.com
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Professor'
              example:
                id: 1
                name: 王教授
                email: asdasd@gamil.com
                createdDate: '2024-10-14T11:39:13.9823506+08:00'
                updatedDate: '2024-10-14T11:39:13.9823508+08:00'
                courses: []
            application/json:
              schema:
                $ref: '#/components/schemas/Professor'
              example:
                id: 1
                name: 王教授
                email: asdasd@gamil.com
                createdDate: '2024-10-14T11:39:13.9823506+08:00'
                updatedDate: '2024-10-14T11:39:13.9823508+08:00'
                courses: []
            text/json:
              schema:
                $ref: '#/components/schemas/Professor'
              example:
                id: 1
                name: 王教授
                email: asdasd@gamil.com
                createdDate: '2024-10-14T11:39:13.9823506+08:00'
                updatedDate: '2024-10-14T11:39:13.9823508+08:00'
                courses: []
  /api/Professors/{id}:
    get:
      tags:
        - Professors
      summary: 授課講師所開課程列表
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProfessorViewModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ProfessorViewModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ProfessorViewModel'
        '204':
          description: No Content
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        courseName:
          type: string
          description: 課程名稱
          nullable: true
        description:
          type: string
          nullable: true
        professorId:
          type: integer
          description: 授課教授Id
          format: int32
          nullable: true
        createdDate:
          type: string
          description: 課程建立時間
          format: date-time
          nullable: true
        updatedDate:
          type: string
          description: 課程更新時間
          format: date-time
          nullable: true
        startTime:
          type: string
          format: date-time
          nullable: true
        endTime:
          type: string
          format: date-span
          nullable: true
        professor:
          $ref: '#/components/schemas/Professor'
        studentCourses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
          nullable: true
      additionalProperties: false
    CourseParamenter:
      type: object
      properties:
        courseName:
          type: string
          description: 課程名稱
          nullable: true
        professorId:
          type: integer
          description: 授課教授Id
          format: int32
          nullable: true
      additionalProperties: false
    CourseViewModel:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        courseName:
          type: string
          description: 課程名稱
          nullable: true
        professorId:
          type: integer
          description: 授課教授Id
          format: int32
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
    Professor:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        name:
          type: string
          description: 教授姓名
          nullable: true
        email:
          type: string
          description: 電子郵件地址
          nullable: true
        createdDate:
          type: string
          description: 帳號建立時間
          format: date-time
        updatedDate:
          type: string
          description: 帳號更新時間
          format: date-time
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
          nullable: true
      additionalProperties: false
    ProfessorParamenter:
      required:
        - email
      type: object
      properties:
        name:
          type: string
          description: 教授姓名
          nullable: true
        email:
          minLength: 1
          type: string
          description: 電子郵件地址
      additionalProperties: false
    ProfessorViewModel:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        name:
          type: string
          description: 教授姓名
          nullable: true
        email:
          type: string
          description: 電子郵件地址
          nullable: true
        courses:
          type: array
          items:
            $ref: '#/components/schemas/CourseViewModel'
          nullable: true
      additionalProperties: false
    Student:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        name:
          type: string
          description: 學生姓名
          nullable: true
        email:
          type: string
          description: 電子郵件地址
          nullable: true
        createdDate:
          type: string
          description: 帳號建立時間
          format: date-time
        updatedDate:
          type: string
          description: 帳號更新時間
          format: date-time
        studentCourses:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'
          nullable: true
      additionalProperties: false
    StudentCourse:
      type: object
      properties:
        id:
          type: integer
          description: 唯一識別碼
          format: int32
        studentId:
          type: integer
          description: 學生Id
          format: int32
        courseId:
          type: integer
          description: 課程Id
          format: int32
        enrollDate:
          type: string
          description: 選課日期
          format: date-time
        course:
          $ref: '#/components/schemas/Course'
        student:
          $ref: '#/components/schemas/Student'
      additionalProperties: false
